### PR TITLE
Created portfolio.py and the Portfolio Class and constructor with som…

### PR DESCRIPTION
**Pull request by EncJon**
…e other methods

### CODE REVIEW

**Review by Dresh13 — CHANGES_REQUESTED** [review]
not implemented properly with respect to simulation model. 
The only data member portfolio has is starting_cash.
Leave accessor method.

**Comment by EncJon** [comment]
To Dan: I left the Portfolio class needing a float to be passed on to it. I do not think the Portfolio class should be in charge of casting to float. When we ask the User what the starting cash is, they can give us an int, and in the prompt, we should immediately cast it to a float to then provide it to other constructors, methods, etc. I think it would be bad coding practice to have the different methods or constructors we will work with have to handle the casting instead of doing it right away in one place. I will write a test class to ensure this happens

**Review by EncJon — COMMENTED** [review]
Changed

**Comment by Dresh13** [comment]
> To Dan: I left the Portfolio class needing a float to be passed on to it. I do not think the Portfolio class should be in charge of casting to float. When we ask the User what the starting cash is, they can give us an int, and in the prompt, we should immediately cast it to a float to then provide it to other constructors, methods, etc. I think it would be bad coding practice to have the different methods or constructors we will work with have to handle the casting instead of doing it right away in one place. I will write a test class to ensure this happens

I never said to cast to float within the portfolio class. we also never established anywhere in our project that we will prompt the user for anything so I am not sure what prompt you are referring to in which we will cast. python has implicit type conversion so it will not be necessary to force to float in the portfolio class as I stated earlier. it is part of our spec to have flexible parameter types. please follow the spec.

**Review by Dresh13 — CHANGES_REQUESTED** [review]
see comment

**Comment by EncJon** [comment]
Updated

**Review by Dresh13 — APPROVED** [review]

**Comment by johnpiapian** [comment]
It looks good to me.

**Review by johnpiapian — APPROVED** [review]

**Pull request merged**
